"use client";
import Image from "next/image";
import { useMemo, useState } from "react";

const products = [
  { id:1, name:"Conjunto sem costura", category:"Conjuntos", price:199.99, image:"/catalogo/conjunto-sem-costura-marrom.jpg", colors:["Preto","Azul-marinho","Marrom"], details:"Conforto e ajuste sem costura para acompanhar todos os movimentos." },
  { id:2, name:"Top sem costura", category:"Tops", price:59.90, image:"/catalogo/top-sem-costura.jpg", colors:["Preto","Azul-marinho","Marrom"], details:"Modelagem confortável, acabamento sem costura e ótima sustentação." },
  { id:3, name:"Regata nadador", category:"Regatas", price:74.90, image:"/catalogo/regata-nadador.jpg", colors:["Branco","Azul-marinho","Preto"], details:"Dry fit encorpado, leve, respirável e com microfuros." },
  { id:4, name:"Conjunto poliamida", category:"Conjuntos", price:249.90, image:"/catalogo/conjunto-poliamida.jpg", colors:["Preto"], details:"Poliamida premium, calça com dois bolsos laterais e top nadador com bojo removível." },
  { id:5, name:"Calça flare + top", category:"Conjuntos", price:249.90, image:"/catalogo/conjunto-flare.jpg", colors:["Preto"], details:"Calça bailarina em poliamida premium e top nadador forrado com bojo removível." },
  { id:6, name:"Regata recorte", category:"Regatas", price:74.90, image:"/catalogo/regata-recorte.jpg", colors:["Preto"], details:"Microfuros, conforto e respirabilidade em uma modelagem feminina." },
  { id:7, name:"Conjunto top + calça com bolso", category:"Conjuntos", price:239.90, image:"/catalogo/conjunto-bolso.jpg", colors:["Marrom"], details:"Poliamida premium, top com recorte e calça com bolso traseiro." },
  { id:8, name:"Macaquinho", category:"Macaquinhos", price:144.90, image:"/catalogo/macaquinho.jpg", colors:["Preto","Marrom"], details:"Poliamida confortável, alças reguláveis e bojo removível." },
  { id:9, name:"Moda Plus Size", category:"Outras linhas", price:null, image:"/catalogo/plus-size.jpg", colors:["Consulte"], details:"Modelagens confortáveis e pensadas para valorizar todos os corpos." },
  { id:10, name:"Linha masculina", category:"Outras linhas", price:null, image:"/catalogo/masculino.jpg", colors:["Consulte"], details:"Peças leves e versáteis para treino e rotina." },
];
const categories=["Todos","Conjuntos","Tops","Regatas","Macaquinhos","Outras linhas"];
const whatsapp="https://wa.me/556184524410";
const money=(value:number|null)=>value===null?"Consulte":value.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});

export default function Home(){
 const [category,setCategory]=useState("Todos"); const [query,setQuery]=useState(""); const [selected,setSelected]=useState<(typeof products)[number]|null>(null);
 const filtered=useMemo(()=>products.filter(p=>(category==="Todos"||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase())),[category,query]);
 const orderLink=(name:string)=>`${whatsapp}?text=${encodeURIComponent(`Olá! Vi o catálogo da Eixo Esportes e quero saber mais sobre: ${name}.`)}`;
 return <main>
  <header className="topbar"><a className="brand" href="#inicio"><span className="brand-mark">E</span><span>EIXO<br/><b>ESPORTES</b></span></a><nav><a href="#catalogo">Catálogo</a><a href="#vantagens">Por que Eixo?</a></nav><a className="button small" href={orderLink("as peças do catálogo")} target="_blank">Falar no WhatsApp</a></header>
  <section className="hero" id="inicio"><div className="hero-copy"><p className="eyebrow">FITNESS FEMININO • BRASÍLIA, DF</p><h1>Movimento que<br/><em>veste você.</em></h1><p className="hero-text">Peças que unem conforto, estilo e qualidade para você se sentir bem dentro e fora do treino.</p><div className="hero-actions"><a className="button" href="#catalogo">Ver coleção</a><span><b>10% OFF</b><small>na primeira compra</small></span></div></div><div className="hero-image"><Image unoptimized src="/catalogo/hero-eixo.jpg" alt="Modelo usando conjunto fitness azul da Eixo Esportes" fill priority sizes="(max-width:760px) 100vw,48vw"/><div className="hero-tag"><span>Nova coleção</span><b>FITNESS</b></div></div></section>
  <section className="catalog" id="catalogo"><div className="section-heading"><div><p className="eyebrow">ESCOLHA SEU LOOK</p><h2>Catálogo Eixo</h2></div><p>Fotografias e produtos da coleção original.</p></div><div className="tools"><div className="filters">{categories.map(item=><button key={item} className={category===item?"active":""} onClick={()=>setCategory(item)}>{item}</button>)}</div><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar peça" aria-label="Buscar peça"/></label></div><div className="product-grid">{filtered.map(product=><article className="product-card" key={product.id} onClick={()=>setSelected(product)} tabIndex={0} onKeyDown={e=>e.key==="Enter"&&setSelected(product)}><div className="product-photo"><Image unoptimized src={product.image} alt={product.name} fill sizes="(max-width:640px) 100vw,(max-width:1000px) 50vw,33vw"/><span>{product.category}</span></div><div className="product-info"><div><h3>{product.name}</h3><p>{product.colors.join(" • ")}</p></div><b>{money(product.price)}</b></div><button className="details">Ver detalhes <span>↗</span></button></article>)}</div>{!filtered.length&&<p className="empty">Nenhuma peça encontrada.</p>}</section>
  <section className="benefits" id="vantagens"><div><p className="eyebrow">FEITO PARA A VIDA REAL</p><h2>Vista sua melhor versão.</h2></div><div className="benefit-list"><p><span>01</span><b>Tecidos confortáveis</b><small>Leves, respiráveis e gostosos no corpo.</small></p><p><span>02</span><b>Modelagens versáteis</b><small>Do treino aos compromissos do dia.</small></p><p><span>03</span><b>Atendimento próximo</b><small>Escolha sua peça direto pelo WhatsApp.</small></p></div></section>
  <section className="coupon"><p>PRIMEIRA COMPRA</p><h2>Seu novo look com <em>10% OFF</em></h2><span>Use o cupom <b>PRIMEIRA10</b> e fale com a gente.</span><a className="button light" href={orderLink("o cupom PRIMEIRA10")} target="_blank">Quero meu desconto</a></section>
  <footer><div className="brand footer-brand"><span className="brand-mark">E</span><span>EIXO<br/><b>ESPORTES</b></span></div><p>Conforto, estilo e qualidade.</p><div><a href="https://instagram.com/eixoesportesdf" target="_blank">@eixoesportesdf</a><a href={whatsapp} target="_blank">(61) 8452-4410</a></div><small>© 2026 Eixo Esportes</small></footer>
  {selected&&<div className="modal-backdrop" onMouseDown={()=>setSelected(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()} role="dialog" aria-modal="true"><button className="close" onClick={()=>setSelected(null)} aria-label="Fechar">×</button><div className="modal-photo"><Image unoptimized src={selected.image} alt={selected.name} fill sizes="(max-width:760px) 100vw,45vw"/></div><div className="modal-copy"><p className="eyebrow">{selected.category}</p><h2>{selected.name}</h2><b className="modal-price">{money(selected.price)}</b><p>{selected.details}</p><div className="color-row">{selected.colors.map(color=><span key={color}>{color}</span>)}</div><a className="button" href={orderLink(selected.name)} target="_blank">Pedir pelo WhatsApp</a></div></div></div>}
  <a className="whatsapp-float" href={orderLink("uma peça")} target="_blank" aria-label="Abrir WhatsApp">●</a>
 </main>;
}
